import { currentUser } from "@clerk/nextjs/server";
import type { Metadata } from "next"; 

export const metadata: Metadata = {
  title: "ADMIN | Qucick-BUS",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user =await currentUser();
  if (user?.publicMetadata?.role !== 'admin') {
    return ;
  } 
  return (
   <div >
     {children}
   </div>
  );
}
